name: Run R Script and Commit Results

# Define when the workflow should run
on:
  push: # The workflow will run on every push to the repository
    branches: [ main ] # Only run for the main branch

# Define the jobs to run
jobs:
  run-r-script:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
    - name: Check out repository
      uses: actions/checkout@v2 # This step checks out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up R
      uses: r-lib/actions/setup-r@v1 # This step sets up an R environment

    - name: Install dependencies
      run: |
        install.packages("remotes")
        remotes::install_deps(dependencies = TRUE)

    - name: Run R script
      run: Rscript run-state-template.R # This step runs your R script

    - name: Commit and push if changes
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add -A
        git commit -m "Automated update" -a || echo "No changes to commit"
        git push
